server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/flow_board_auth_service_db
    username: root
    password: ${db_password}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}


  jpa:
    hibernate:
      ddl-auto: update

  boot:
    admin:
      client:
        url: http://localhost:9090

  management:
    endpoints:
      web:
        exposure:
          include: "*"

    endpoint:
      health:
        show-details: always

security:
  jwt:
    secret: ${jwt-secret-key}

brevo:
  api-key: ${brevo-api-key}
  sender:
    email: ${brevo-sender-mail}
    name: FlowBoard

domain:
  url: "http://localhost:8081/api/v1/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

admin:
  verification:
    mail: ${admin-verification-mail}