server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/flow_board_auth_service_db
    username: root
    password: ${db_password:${DB_PASSWORD:root}}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id:${GOOGLE_CLIENT_ID}}
            client-secret: ${google_client_secret:${GOOGLE_CLIENT_SECRET}}
            redirect-uri: ${google_redirect_uri:${GOOGLE_REDIRECT_URI:http://localhost:8081/login/oauth2/code/google}}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp_username:${SMTP_USERNAME}}
    password: ${smtp_app_password:${SMTP_APP_PASSWORD}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

security:
  jwt:
    secret: ${jwt_secret_key:${JWT_SECRET_KEY}}

admin:
  email: devarshim973@gmail.com
  password: $2a$10$EfYecqasrVgIE4uZyeGhBOZd7OsMWUGtIsNxToQAtVYkwfXLrPF0C

app:
  frontend:
    url: ${frontend_url:${FRONTEND_URL:http://localhost:5173}}
  mail:
    from:
      email: ${smtp_from_email:${SMTP_FROM_EMAIL}}
      name: ${smtp_from_name:${SMTP_FROM_NAME:FlowBoard}}

domain:
  url: "http://localhost:8081/api/v1/"

eureka:
  client:
    service-url:
      defaultZone: ${eureka_default_zone:${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true