spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/flowboard_auth
    username: root
    password: ${db_password}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}


  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${jwt-secret-key}

brevo:
  api-key: ${brevo-api-key}
  sender:
    email: ${brevo-sender-mail}
    name: FlowBoard

domain:
  url: "http://localhost:8080/api/v1/"