server:
  port: 8082

spring:
  application:
    name: notification-service

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/flowboard_auth
    username: root
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${jwt-secret-key}

app:
  mail:
    sender-name: FlowBoard

domain:
  url: "http://localhost:8080/api/v1/"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
