server:
  port:
    8088

spring:
  application:
    name: subscription-service

  datasource:
    url: jdbc:mysql://localhost:3306/flow_board_subscription_service_db
    username: root
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update

  boot:
    admin:
      client:
        url: http://localhost:9090

  management:
    endpoints:
      web:
        exposure:
          include: "*"

    endpoint:
      health:
        show-details: always



razorpay:
  key-id: ${RAZOR_PAY_API_KEY}
  key-secret: ${RAZOR_PAY_SECRET_KEY}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true